[workspace]
members = [
    "leptos-daisyui-rs",
    "leptos-daisyui-cli",
    "demo",
    "demo-macros",
]
resolver = "2"

[workspace.package]
version = "0.0.4"
edition = "2024"
license = "MIT"
repository = "https://github.com/noshishiRust/leptos-daisyui-rs"
