[package]
name = "demo-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.74"
quote = "1.0.36"
pastey = "0.2.1"
proc-macro2 = "1.0.86"
heck = "0.5"
comrak = "0.31"
